main_app/api/urls.py
from django.urls import path

from . import views

app_name = 'articles'

urlpatterns = [
    path('article/', views.ArticleView.as_view()),
    path('article/<int:pk>', views.SingleArticleView.as_view()),
    path('user/', views.UserView.as_view()),
    path('user/<int:pk>', views.UserDetail.as_view()),
]

main_app/urls.py
from django.conf import settings
from django.urls import path
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    path('', views.MainPage.as_view(), name='index'),
    path('article/new', views.ArticleView.as_view(request_type='CREATE'), name='new_post'),
    path('article/<slug:article_slug>', views.ArticlePage.as_view(), name='article_detail'),
    path('article/<int:article_id>/delete', views.ArticleView.delete, name='delete_article'),
    path('article/<slug:article_slug>/edit', views.ArticleView.as_view(request_type='UPDATE'), name='edit_article'),
    path('article/<int:article_id>/add_like', views.LikeDislike.as_view(vote_type=True), name='add_like'),
    path('article/<int:article_id>/add_dislike', views.LikeDislike.as_view(vote_type=False), name='add_dislike'),
    path('articles/user/<str:username>', views.UserArticle.as_view(), name='user_articles'),
    path('registration', views.RegisterFormView.as_view(), name='register'),
    path('user/<str:username>', views.UserView.as_view(template_name='main_app/user_profile.html'),
         name='user_profile'),
    path('user/<str:username>/edit/', views.UserView.as_view(template_name='main_app/edit_user_profile.html'),
         name='edit_profile'),
    path('get_online/', views.get_online, name='get_online'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main_app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('social_django.urls', namespace='social')),
    path('api/v1/', include('main_app.api.urls', namespace='api')),
]

main_app/models.py
from ckeditor.fields import RichTextField
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.html import mark_safe
from django.utils import timezone
from django.utils.text import slugify

from . import managers


class CustomUser(AbstractUser):
    avatar = models.ImageField(upload_to='images/for_profile', null=True, blank=True)
    last_online = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.email

    def is_online(self):
        if self.last_online:
            return (timezone.now() - self.last_online) < timezone.timedelta(minutes=10)
        return False

    def image_in_admin(self):
        return mark_safe(f'<img src="/media/{self.avatar}" width="110" height="110" style="object-fit: cover;" />')

    image_in_admin.short_description = 'profile images'


class Article(models.Model):
    class Meta:
        db_table = 'article'

    title = models.CharField(max_length=150)
    slug = models.SlugField(max_length=40)
    image = models.ImageField(upload_to='images/for_article', null=True, blank=True)
    text = RichTextField()
    short_description = models.CharField(max_length=120, null=True, blank=True)
    date = models.DateTimeField(auto_now=True)
    author = models.ForeignKey('main_app.CustomUser', on_delete=models.CASCADE, blank=True, null=True)

    objects = managers.ArticleQuerySet.as_manager()

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        return super(Article, self).save(*args, **kwargs)


class Comment(models.Model):
    class Meta:
        db_table = 'comment'
    text = RichTextField()
    date = models.DateTimeField(auto_now=True)
    article = models.ForeignKey('main_app.Article', on_delete=models.CASCADE)
    author = models.ForeignKey('main_app.CustomUser', on_delete=models.CASCADE)


class Like(models.Model):
    user = models.ForeignKey('main_app.CustomUser', on_delete=models.CASCADE)
    article = models.ForeignKey('main_app.Article', on_delete=models.CASCADE)
    is_liked = models.BooleanField()

main_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser,  Article, Comment


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
        )


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = (
            'username',
            'email',
            'avatar',
        )


class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = (
            'title',
            'text',
            'short_description',
            'image',
        )


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = (
            'text',
        )

main_app/api/views.py
from rest_framework.generics import GenericAPIView, RetrieveUpdateDestroyAPIView, RetrieveUpdateAPIView
from rest_framework.generics import get_object_or_404
from rest_framework.mixins import ListModelMixin, CreateModelMixin

from .serializers import ArticleSerializer, UserSerializer
from ..models import Article, CustomUser


class ArticleView(ListModelMixin, CreateModelMixin, GenericAPIView):
    queryset = Article.objects.all()
    serializer_class = ArticleSerializer

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)

    def perform_create(self, serializer):
        author = get_object_or_404(CustomUser, id=self.request.data.get('author'))
        return serializer.save(author=author)


class SingleArticleView(RetrieveUpdateDestroyAPIView):
    queryset = Article.objects.all()
    serializer_class = ArticleSerializer


class UserView(ListModelMixin, CreateModelMixin, GenericAPIView):
    queryset = CustomUser.objects.all()
    serializer_class = UserSerializer

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)


class UserDetail(RetrieveUpdateAPIView):
    queryset = CustomUser.objects.all()
    serializer_class = UserSerializer

main_app/views.py
import random

from django.core.paginator import Paginator
from django.db.models import Count
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.views.generic import View, FormView

from .forms import ArticleForm, CommentForm, CustomUserCreationForm
from .models import Article, Comment, Like, CustomUser


class MainPage(View):
    articles_queryset = Article.objects.get_articles()
    comments_queryset = Comment.objects.order_by('-date')
    template_name = 'main_app/basic_page.html'
    AMOUNT_LAST_COMMENTS = 4
    AMOUNT_RANDOM_ARTICLES = 3

    def get_random_articles(self):
        # Get id all articles
        id_articles = list(Article.objects.values_list('id', flat=True))

        # Get random id
        random_ids = random.sample(id_articles, self.AMOUNT_RANDOM_ARTICLES)

        # Get random articles
        articles = self.articles_queryset.filter(id__in=random_ids)

        return articles

    def get(self, request):
        # Random article for main interactive
        random_articles = self.get_random_articles()

        # Last comments
        last_comments = self.comments_queryset[:self.AMOUNT_LAST_COMMENTS]

        # Paginator
        paginator = Paginator(self.articles_queryset, 8)
        page = request.GET.get('page')
        articles = paginator.get_page(page)

        return render(
            request,
            self.template_name,
            {
                'main_article': random_articles[0],
                'main_articles': random_articles[1:3],
                'articles': articles,
                'comments': last_comments,
            },
        )


class UserArticle(View):
    articles_queryset = Article.objects.get_articles()
    comments_queryset = Comment.objects.order_by('-date')
    template_name = 'main_app/articles_created_by_user.html'
    AMOUNT_LAST_COMMENTS = 4

    def get(self, request, **kwargs):
        user = CustomUser.objects.get(username=kwargs['username'])

        # Get last comments
        last_comments = self.comments_queryset[:self.AMOUNT_LAST_COMMENTS]

        # Paginator
        paginator = Paginator(self.articles_queryset.filter(author_id=user.id), 8)
        page = request.GET.get('page')
        articles = paginator.get_page(page)

        return render(
            request,
            self.template_name,
            {
                'articles': articles,
                'comments': last_comments,
                'user': user,
            }
        )


class RegisterFormView(FormView):
    form_class = CustomUserCreationForm
    success_url = "/"
    template_name = 'registration/register.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponse(status=404)
        return render(
            request,
            self.template_name,
        )

    def form_valid(self, form):
        form.save()
        return super(RegisterFormView, self).form_valid(form)


class UserView(View):
    # Template name transmitted from url
    template_name = None

    @staticmethod
    def post(request, username):
        user = CustomUser.objects.get(username=username)
        user.username = request.POST.get('username')
        user.first_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')
        if request.FILES.get('images'):
            user.avatar = request.FILES.get('images')
        user.save()
        return redirect(
            'user_profile',
            username=username
        )

    def get(self, request, username):
        user = CustomUser.objects.get(username=username)
        return render(
            request,
            self.template_name,
            {
                'is_my_profile': request.user.id == user.id,
                'user_article_count': Article.objects.filter(author_id=user.id).count(),
                'user_comment_count': Comment.objects.filter(author_id=user.id).count(),
                'user_likes_count': Like.objects.filter(user_id=user.id, is_liked=True).count(),
                'user': user
            }
        )


class ArticlePage(View):
    form_class = CommentForm
    template_name = 'main_app/article.html'
    AMOUNT_LAST_ARTICLES = 2

    def post(self, request, **kwargs):
        article = Article.objects.get(slug=kwargs['article_slug'])
        form = self.form_class(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.article = article
            comment.author = request.user
            comment.save()
            return redirect('article_detail', article_slug=kwargs['article_slug'])

    def get(self, request, **kwargs):
        article = Article.objects.get_like_dislike_percent().get(slug=kwargs['article_slug'])
        return render(
            request,
            self.template_name,
            {
                'form': self.form_class,
                'last_articles': Article.objects.filter(
                    author_id=article.author_id
                ).order_by('-date')[:self.AMOUNT_LAST_ARTICLES],
                'article': article,
                'is_liked': Like.objects.filter(article_id=article.id, user_id=request.user.id),
                'all_likes': Like.objects.filter(article_id=article.id, is_liked=True).count(),
                'marks': Like.objects.filter(article_id=article.id).values('is_liked').annotate(
                    count=Count('is_liked')).order_by('-is_liked'),
                'like_percent': article.liked,
                'dislike_percent': article.disliked,
                'comment': Comment.objects.filter(article_id=article.id).order_by('-date'),
            }
        )


class ArticleView(View):
    form_class = ArticleForm
    template_name = 'main_app/article_edit.html'
    request_type = None

    def delete(self, **kwargs):
        article = Article.objects.get(id=kwargs['article_id'])
        article.delete()
        return redirect('/')

    def post(self, request, **kwargs):
        form = ArticleForm(request.POST, request.FILES)

        # If create new article
        if self.request_type == 'CREATE':
            if form.is_valid():
                article = form.save(commit=False)
                article.author = request.user
                article.save()
                return redirect(
                    'article_detail',
                    article_slug=article.slug
                )

        # If edit article
        elif self.request_type == 'UPDATE':
            article = get_object_or_404(Article, slug=kwargs['article_slug'])
            article.title = request.POST.get('title')
            article.text = request.POST.get('text')
            article.short_description = request.POST.get('short_description')
            if request.FILES.get('images'):
                article.image = request.FILES.get('images')
            article.save()
            return redirect(
                'article_detail',
                article_slug=article.slug
            )

    def get(self, request, **kwargs):
        article = get_object_or_404(
            Article,
            slug=kwargs['article_slug']
        ) if 'article_slug' in kwargs else None
        return render(
            request,
            'main_app/article_edit.html',
            {
                'article': article,
                'form': self.form_class(request.POST or None, request.FILES or None, instance=article),
                'type': self.request_type,
            }
        )


class LikeDislike(View):
    # Vote type transmitted from url
    vote_type = None

    def get(self, request, article_id):
        Like.objects.create(user_id=request.user.id, article_id=article_id, is_liked=self.vote_type)
        return redirect(
            'article_detail',
            article_slug=Article.objects.get(id=article_id).slug
        )


def get_online(request):
    try:
        user = CustomUser.objects.get(pk=request.user.id)
        user.last_online = timezone.now()
        user.save()
        return HttpResponse({'status': 'Success'})
    except CustomUser.DoesNotExist:
        return HttpResponse({'status': 'Fail'})

main_app/templates/main_app/article.html
{% extends 'main_app/basic_page.html' %}
{% load humanize %}
{% load static %}
{% block content %}
    <div class="page_article_image"
         style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url('{{ article.image.url }}');">
        <div class="text_in_article_image">
            <h1>{{ article.title }}</h1>
        </div>
    </div>
    <div class="background_for_page_image"></div>
    <div class="top_border_blog_info"></div>
    <div class="blog">
        <div class="blog_info">
            <span class="blog_data">{{ article.date.date }}</span>
            <a href="{% url 'user_profile' article.author.username %}" class="blog_author_name">
                {{ article.author.get_full_name }}
            </a>
            <div class="quantity_comment">
                <strong>COMMENTS: {{ comment.count }}</strong>
            </div>
            <div class="quantity_likes">
                <strong>LIKES: {{ all_likes }}</strong>
            </div>
        </div>
        <div class="blog_text">
            {% autoescape off %}
                <p>{{ article.text }}</p>
            {% endautoescape %}
            {% if request.user.is_authenticated %}
                {% if is_liked %}
                    <div class="marks_diagram">
                        {% for mark in marks %}
                            {% if mark.is_liked %}
                                <div class="like_diagram">
                                    <div class="text_in_marks">
                                        <p class="left">{{ mark.count }}</p>
                                        <img src="{% static 'images/like.png' %}" alt="like">
                                    </div>
                                </div>
                            {% elif not mark.is_liked and marks|length == 1 %}
                                <div class="like_diagram">
                                    <div class="text_in_marks">
                                        <p class="left">0</p>
                                        <img src="{% static 'images/like.png' %}" alt="like">
                                    </div>
                                </div>
                            {% endif %}

                            {% if forloop.counter == 1 %}
                                <div class="marks_statistics">
                                    <div class="statistics_like" style="width: {{ like_percent }}%;"></div>
                                    <div class="statistics_dislike" style="width: {{ dislike_percent }}%;"></div>
                                </div>
                            {% endif %}

                            {% if not mark.is_liked %}
                                <div class="dislike_diagram">
                                    <div class="text_in_marks">
                                        <img src="{% static 'images/dislike.png' %}" alt="dislike">
                                        <p class="right">{{ mark.count }}</p>
                                    </div>
                                </div>
                            {% elif mark.is_liked and marks|length == 1 %}
                                <div class="dislike_diagram">
                                    <div class="text_in_marks">
                                        <img src="{% static 'images/dislike.png' %}" alt="dislike">
                                        <p class="right">0</p>
                                    </div>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                {% else %}
                    <div class="like_dislike">
                        <a class="like" href="{% url 'add_like' article.id %}">
                            <div class="text_in_marks">
                                <img src="{% static 'images/like.png' %}" alt="like">
                                <p class="like_it">I LIKE IT</p>
                            </div>
                        </a>
                        <a class="dislike" href="{% url 'add_dislike' article.id %}">
                            <div class="text_in_marks">
                                <img src="{% static 'images/dislike.png' %}" alt="dislike">
                                <p class="dislike_it">I DON'T LIKE IT</p>
                            </div>
                        </a>
                    </div>
                {% endif %}
            {% endif %}
        </div>
        <div class="authholder">
            <div class="author">
                <div class="author_img">
                    <img src="{{ article.author.avatar.url }}" alt="author_avatar">
                </div>
                <div class="body">
                    <div class="name">Автор:
                        <strong>{{ article.author.get_full_name }}</strong>
                    </div>
                    <a href="{% url 'user_articles' article.author.username %}" class="more">All articles of this
                        author</a>
                </div>
            </div>
            <div class="authmats">
                <strong>Последние статьи автора:</strong>
                {% for last_article in last_articles %}
                    <p>
                        <a class="last_articles" href="{% url 'article_detail' last_article.slug %}">
                            {{ last_article.title }}
                        </a>
                    </p>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="comment_body">
        <div class="comment_count">
            <div class="comments">COMMENTS:</div>
        </div>
        <div class="comment_main">
            {% if request.user.is_authenticated %}
                <div class="comment_new">
                    <img src="{{ user.avatar.url }}" alt="user_avatar">
                    <form method="POST" class="post-form">
                        {% csrf_token %}
                        <div class="comment_input_and_save">
                            <div class="comments_info">
                                {{ form.media }}
                                {{ form.text }}
                            </div>
                            <button type="submit" class="send_comment">Send</button>
                        </div>
                    </form>
                </div>
            {% endif %}
            {% autoescape off %}
                {% for comment_in_article in comment %}
                    <div class="comment_in_article">
                        <img src="{{ comment_in_article.author.avatar.url }}" alt="comment_author_avatar">
                        <div class="comment_info">
                            <div class="comment_image_date">
                                <a href="{% url 'user_profile' comment_in_article.author.id %}">
                                    {{ comment_in_article.author.get_full_name }}
                                </a>
                                <span aria-hidden="true">•</span>
                                <p>{{ comment_in_article.date|naturaltime }}</p>
                            </div>
                            <p class="comment_text">{{ comment_in_article.text }}</p>
                        </div>
                    </div>
                {% endfor %}
            {% endautoescape %}
        </div>
    </div>
{% endblock %}

main_app/templates/main_app/article_edit.html
{% extends 'main_app/basic_page.html' %}

{% block content %}
    <div class="main_new_article">
        <div class="white_background_above_profile"></div>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="new_article">
                <p>New post</p>
            </div>
            <div class="body_new_article">
                <div class="create_new_article">
                    <div class="new_article_title">
                        <label for="id_title">
                            Title:
                        </label>
                        {% if type == 'CREATE' %}
                            <textarea id="id_title"
                                      maxlength="90"
                                      name="title"
                                      required
                            ></textarea>
                        {% else %}
                            <textarea id="id_title"
                                      maxlength="90"
                                      name="title"
                                      required
                            >{{ article.title }}</textarea>
                        {% endif %}
                    </div>
                    <div class="new_article_text">
                        <label for="id_text">
                            Text:
                        </label>
                        <div>
                            {{ form.media }}
                            {{ form.text }}
                        </div>
                    </div>
                    <div class="new_article_short_description">
                        <label for="id_short_description">
                            Short description:
                        </label>
                        {% if type == 'CREATE' %}
                            <textarea name="short_description"
                                      maxlength="120"
                                      id="id_short_description"
                                      required></textarea>
                        {% else %}
                            <textarea name="short_description"
                                      maxlength="120"
                                      id="id_short_description"
                                      required
                            >{{ article.short_description }}</textarea>
                        {% endif %}
                    </div>
                    <div class="new_article_image">
                        <label class="label_new_image">
                            Image:
                        </label>
                        <input type="file"
                               class="inputfile"
                               required
                               oninput="upload_article_image()"
                               name="image"
                               accept="image/*"
                               id="id_image"
                               data-multiple-caption="{count} files selected"
                               multiple/>
                        <label for="id_image">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="17" viewBox="0 0 20 17">
                                <path d="M10 0l-5.2 4.9h3.3v5.1h3.8v-5.1h3.3l-5.2-4.9zm9.3
                                11.5l-3.2-2.1h-2l3.4 2.6h-3.5c-.1 0-.2.1-.2.1l-.8
                                2.3h-6l-.8-2.2c-.1-.1-.1-.2-.2-.2h-3.6l3.4-2.6h-2l-3.2 2.1c-.4.3-.7
                                1-.6 1.5l.6 3.1c.1.5.7.9 1.2.9h16.3c.6
                                0 1.1-.4 1.3-.9l.6-3.1c.1-.5-.2-1.2-.7-1.5z">
                                </path>
                            </svg>
                            <span class="replace">
                                Choose a file…
                            </span>
                        </label>
                        <button type="submit" class="save_new_article">
                            Save
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

main_app/templates/main_app/articles_created_by_user.html
{% extends 'main_app/basic_page.html' %}
{% load staticfiles %}
{% block article_create %}
<div class="all_articles">
{% include 'main_app/main_for_user_articles.html' %}
{% endblock %}
</div>

main_app/templates/main_app/user_profile.html
{% extends 'main_app/basic_page.html' %}
{% block content %}
<div class="body_profile">
    <div class="white_background_above_profile">
        {% if not is_my_profile %}
            <div class="report" style="width: max-content; padding-top: 2.29%; margin-left: 30px;">
                <a href="#" style="
                text-transform: uppercase;
                padding: 0 6px 0 6px;
                border-radius: 5px 5px 0 0;
                background-color: #738589;
                color: #264041;
                font-weight: 700;
                font-size: 13px;">пожаловаться</a>
            </div>
        {% endif %}
    </div>
    <div class="report_profile">
        {% if is_my_profile %}
            <div class="change_profile">
                <a href="{% url 'edit_profile' request.user.username %}">Изменить профиль</a>
        {% else %}
            <div class="change_profile">
                <a href="#">Подписаться</a>
        {% endif %}
        </div>
    </div>
    <div class="main_profile">
        <div class="white_background_above_main"></div>
        <div class="about_profile">
            <div class="profile_info_img">
                <img src="{{ user.avatar.url }}" style="      margin-left: 235px;
                                                        height: 178px;
                                                        width: 178px;
                                                        object-fit: cover;
                                                        margin-top: -15px;
                                                        border: 3px solid #fff;">
                <div class="profile_info">
                    <div class="profile_name">
                        <a>{{ user.get_full_name }}</a>
                        {% if user.is_online %}
                            <div class="user_online"></div>
                        {% else %}
                            <div class="user_offline"></div>
                        {% endif %}
                    </div>
                <a class="username">USERNAME: {{ user.username }}</a>
                </div>
            </div>
            <div class="statistic_user">
                <div class="statistic">
                    <div class="text_in_statistic">
                        <a href="{% url 'user_articles' user.username %}" id="statistic_article">
                            Статьи
                        </a>
                    </div>
                    <div class="number_for_article">
                        <a>{{ user_article_count }}</a>
                    </div>
                </div>
                <div class="subscribers">
                    <div class="text_in_statistic">
                        <a id="statistic_subscribers">Подписчики</a>
                    </div>
                    <div class="number_for_subscribers">
                        <a>NONE</a>
                    </div>
                </div>
                <div class="subscriptions">
                    <div class="text_in_statistic">
                        <a id="statistic_subscriptions">Подписки</a>
                    </div>
                    <div class="number_for_subscriptions">
                        <a>NONE</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="cursor_pointer">
            <div class="statistic_info_background"  onclick="open_statistic()">
                <div class="main_statistic_button">
                    <div class="body_statistic_button">
                        <div class="statistic_button" id="statistic_button"></div>
                        <p class="statistic_name">СТАТИСТИКА</p>
                    </div>
                </div>
                <div class="white_background_statistic" id="body_statistic">
                    <div class="body_with_statistic" id="block_with_statistic">
                        <div class="statistic_comments">
                            <div class="body_white_strip">
                                <div class="white_strip"></div>
                            </div>
                            <div class="text_in_body_statistic">комментарии: {{user_comment_count}}</div>
                        </div>
                        <div class="statistic_likes">
                            <div class="display_statistic_likes">
                                <div class="body_white_strip">
                                    <div class="white_strip"></div>
                                </div>
                                <div class="text_in_body_statistic">нравится: {{ user_likes_count }}</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}